version: '3.4'

services:
    reverse:
        container_name: reverse
        hostname: reverse
        image: nginx
        ports: 
            - 80:80
            - 443:443
        volumes: 
    axotl:
        build: 
            context: .
            dockerfile: Dockerfile
        environment:
        ports: 
            - 80:3000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 1m30s
            timeout: 1m30s
            retries: 3
            start_period: 1m