export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const USER_FAILED = 'USER_FAILED'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RES_PASSWORD = 'RES_PASSWORD'


//Hackathon Actions
export const GET_HACKATHONS = 'GET_HACKATHONS';
export const GET_HACKATHONS_FAIL = 'GET_HACKATHONS_FAIL';
export const CREATE_HACKATHON = 'CREATE_HACKATHON';
export const CREATE_HACKATHON_FAIL = 'CREATE_HACKATHON_FAIL';